const gallery = [
    {id:1,  file:'1.png'  ,  year:2020,  featured:true,  type:'image'  },
    {id:2,  file:'2.png'  ,  year:2020,  featured:false, type:'image'  },
    {id:3,  file:'3.png'  ,  year:2020,  featured:true,  type:'image'  },
    {id:4,  file:'4.png'  ,  year:2020,  featured:false, type:'image'  },
    {id:5,  file:'5.png'  ,  year:2020,  featured:true,  type:'image'  },
    {id:6,  file:'6.png'  ,  year:2020,  featured:false, type:'image'  },
    {id:7,  file:'7.png'  ,  year:2020,  featured:true,  type:'image'  },
    {id:8,  file:'8.png'  ,  year:2020,  featured:false, type:'image'  },
    {id:9,  file:'9.png'  ,  year:2020,  featured:true,  type:'image'  },
    {id:10,  file:'10.png',  year:2021,  featured:false, type:'image'  },
    {id:11,  file:'11.png',  year:2021,  featured:true,  type:'image'  },
    {id:12,  file:'12.png',  year:2021,  featured:false, type:'image'  },
    {id:13,  file:'13.png',  year:2021,  featured:true,  type:'image'  },
    {id:14,  file:'14.png',  year:2021,  featured:false, type:'image'  },
    {id:15,  file:'15.png',  year:2021,  featured:true,  type:'image'  },
    {id:16,  file:'16.png',  year:2021,  featured:false, type:'image'  },
    {id:17,  file:'17.png',  year:2021,  featured:true,  type:'image'  },
    {id:18,  file:'18.png',  year:2021,  featured:false, type:'image'  },
    {id:19,  file:'19.png',  year:2022,  featured:true,  type:'image'  },
    {id:20,  file:'20.png',  year:2022,  featured:false, type:'image'  },
    {id:21,  file:'21.png',  year:2022,  featured:true,  type:'image'  },
    {id:22,  file:'22.png',  year:2022,  featured:false, type:'image'  },
    {id:23,  file:'23.png',  year:2022,  featured:true,  type:'image'  },
    {id:24,  file:'24.png',  year:2022,  featured:false, type:'image'  },
]

export default gallery